#concat:
#  from: concat
#  to: lower_case
#  filter: ConcatenationFilter
lower_case:
  from: lower_case
  to: reverse
  filter: LowerCaseFilter
reverse:
  from: reverse
  to: result
  filter: ReverseFilter
result:
  from: result